SVLS-4605 - Improve agent and tracer logs in AAS Linux
DataDog/datadog-aas-linux pull request #36
Opened 2024-04-24 19:57 UTC by TophrC-dd

### What this does 
This PR updates the datadog wrapper to set the trace logging directory which will allow a consistent logging experience when combined with the configuration files also provided in this script. It will keep agent and dogstatsD logs in a single place based on the version of the wrapper. Also in the configuration file it is setting some Azure specific values for cloud metadata and also disabling general metadata collection.

2024-04-24 20:25 UTC, jcstorms1 requested changes

2024-04-24 20:25 UTC, jcstorms1 commented on datadog.yaml
> +  enabled: true
I think we can eliminate this part actually. It is set by the customer as env vars. Do you have time to test it?

2024-04-24 20:25 UTC, jcstorms1 commented on dogstatsd.yaml
> +use_dogstatsd: true
Same thing here as I mentioned above.

2024-04-25 01:33 UTC, jcstorms1 approved these changes

2024-05-10 18:05 UTC, duncanpharvey requested changes
LGTM with one minor fix!

2024-05-10 18:05 UTC, duncanpharvey commented on datadog_wrapper
> +        DD_BINARIES_URL="https://github.com/TophrC-dd/datadog-aas-linux/releases/download"
Change back to DataDog

2024-05-10 18:13 UTC, TophrC-dd commented on datadog_wrapper
> +        DD_BINARIES_URL="https://github.com/TophrC-dd/datadog-aas-linux/releases/download"
Done!

2024-05-10 18:15 UTC, duncanpharvey approved these changes

2024-05-17 14:50 UTC, merged